workflow:
  rules:
    # run always for merge requests
    - if: $CI_MERGE_REQUEST_IID
    # allow running manually (on any branch)
    - if: $CI_PIPELINE_SOURCE == "web"
    # run always on master/main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # optional - run always on develop branch
    - if: $CI_COMMIT_BRANCH == "develop"
 
sonarqube-check:
  image:
    name: artifactory.sofa.dev/docker-remote/sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - "${SONAR_USER_HOME}/cache"
    policy: pull-push
  script:
    - sonar-scanner
