---
variables:
  DOCKER_IMAGE_VERSION: "1.0"
  DOCKER_IMAGE_NAME: cdpcli-ddp
  DOCKER_IMAGE_URL: $DOCKER_REGISTRY/$ARTIFACTORY_REPOSITORY_NAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
  ENV_NAME: cdp-devo-lab-env01
  CML_CLUSTER_NAME: cdp-devo-lab-env01-cml01

image: ${DOCKER_IMAGE_URL}

default:
  tags:
    - docker

stages:
  - cml_provision
  - cml_delete

include:
  - cml/cml_provision.yml
