---
variables:
  DOCKER_IMAGE_VERSION: "1.0"
  DOCKER_IMAGE_NAME: cdpcli-ddp
  DOCKER_IMAGE_URL: $DOCKER_REGISTRY/$ARTIFACTORY_REPOSITORY_NAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
  ENV_NAME: cdp-devo-lab-env01
  CML_CLUSTER_NAME: cdp-devo-lab-env01-cml01
  ACTION: delete

image: ${DOCKER_IMAGE_URL}

default:
  tags:
    - docker

stages:
  - start_env
  - manage
  - stop_env

cdp_env_start:
  stage: start_env
  script:
    - cdp environments start-environment --environment-name $ENV_NAME || true
    - timeout 20m bash cdp-env/wait_for_status.sh "AVAILABLE"
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $ACTION == "provision"

cdp_env_stop:
  stage: stop_env
  script:
    - cdp environments stop-environment --environment-name $ENV_NAME || true
    - timeout 20m bash cdp-env/wait_for_status.sh "ENV_STOPPED"
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $ACTION == "delete"
