import sys
import json
import os

# there is a bit of a challenge since the cluster id is dynamically generated by CDP and cannot
# be known beforehand

def get_cluster_id(cde_cluster_name):
    with open("services.json") as json_file:
        services = json.load(json_file)

    for service in services["services"]:
        if service["name"] == cde_cluster_name:
            return service["clusterId"]

def get_vc_id(all_vcs, vc_name):
    for vc in all_vcs["vcs"]:
        if vc["vcName"] == vc_name:
            return vc["vcId"]