import sys
import json
import os

# there is a bit of a challenge since the cluster id is dynamically generated by CDP and cannot
# be known beforehand
with open("services.json") as json_file:
    services = json.load(json_file)

for service in services["services"]:
    if service["name"] == os.getenv("CDE_CLUSTER_NAME"):
        cluster_id = service["clusterId"]
print(cluster_id)
