import sys
import json
import os

# there is a bit of a challenge since the cluster id is dynamically generated by CDP and cannot
# be known beforehand
with open("services.json") as json_file:
    services = json.load(json_file)

for cluster_name in os.getenv("CDE_CLUSTERS").split():
    for service in services["services"]:
        if service["name"] == cluster_name:
            with open(f"{cluster_name}_cid.txt", "w", encoding="utf-8") as f:
                f.write(service["clusterId"])
