---
cml_provision:
  stage: cml_provision
  tags:
    - docker
  before_script:
    - cdp ml create-workspace --generate-cli-skeleton > skel.json
  script:
    - cat skel.json | python3 cml/cml_json_create.py
    - cat *env.json
    # - cdp --debug ml create-workspace --cli-input-json file://env.json
  artifacts:
    paths:
      - skel.json
      - env.json
    expire_in: 30 days
    when: always
  # when: manual
  # only:
  #   - main

cml_delete:
  stage: cml_delete
  tags:
    - docker
  script: cdp --debug ml delete-workspace --no-force --remove-storage --environment-name $ENV_NAME --workspace-name $WORKSPACE_NAME
  when: manual
  # only:
  #   - main
