---
- hosts: localhost
  connection: local
  vars:
    ecb_env: "{{ lookup('env', 'ECB_ENV') }}"
    env_name: "{{ lookup('env', 'CDP_ENV_NAME') }}"

    # CDW
    # we need this variable since we enable the CDW service in reduced permission mode and that can only be done via GUI
    cdw_ready: true

  vars_files:
    - "cdp_envs/{{ ecb_env }}/{{ env_name }}/env.yml"
    - "cdp_envs/{{ ecb_env }}/{{ env_name }}/cdl.yml"
    - "cdp_envs/{{ ecb_env }}/{{ env_name }}/cde.yml"
    - "cdp_envs/{{ ecb_env }}/{{ env_name }}/cml.yml"
    - "cdp_envs/{{ ecb_env }}/{{ env_name }}/cdw.yml"
    - "cdp_envs/{{ ecb_env }}/tenant.yml"

  collections:
    - cloudera.cloud

  roles:
    - cred
    - env
    - cdl
  tasks:
    - include_role:
        name: cde
      vars:
        cde_cluster: "{{ item.value }}"
        cde_cluster_name: "{{ item.key }}"
      with_dict: "{{ cde_clusters }}"

    # - include_role:
    #     name: cml
    #   vars:
    #     cml_cluster: "{{ cml_clusters[item] }}"
    #     cml_cluster_name: "{{ item }}"
    #   with_items: "{{ cml_cluster_names }}"

    # - include_role:
    #     name: cdw
    #   when: cdw_ready

    # - include_role:
    #     name: cdw_vw
    #   vars:
    #     cdw_vw: "{{ cdw_vws[item] }}"
    #     cdw_vw_name: "{{ item }}"
    #   with_items: "{{ cdw_vw_names }}"
    #   when: cdw_ready
