---
# in vars folder apparently only the main.yml is verified and we would like to separate the vars per cdp component
- include_vars:
    dir: vars

# we cannot use the inventory since we are running the playbook on localhost
- include_vars:
    dir: "../../../group_vars/{{ ecb_env }}"

# - name: Create credential
#   cloudera.cloud.env_cred:
#     state: present
#     cloud: aws
#     name: "{{ env_credential['credential_name'] }}"
#     description: "{{ env_credential['description'] }}"
#     role: "{{ env_credential['role_arn'] }}"
# - name: Install environment
#   cloudera.cloud.env:
#     name: "{{ env_name }}"
#     state: present
#     vpc_id: "{{ env_vpc_id }}"
#     credential: "{{ env_credential['credential_name'] }}"
#     cloud: aws
#     region: "{{ env_region }}"
#     log_location: "{{ env_log_bucket }}"
#     log_identity: "{{ env_log_role_instance_profile }}"
#     public_key_text: "{{ env_public_key }}"
#     default_sg: "{{ env_sg }}"
#     knox_sg: "{{ env_sg }}"
#     subnet_ids: "{{ env_subnets }}"
#     workload_analytics: "{{ env_workload_analytics }}"
#     tags: "{{ env_tags }}"
#     tunnel: false
# - name: Create data access mappings for ID Broker
#   cloudera.cloud.env_idbroker:
#     name: "{{ env_name }}"
#     data_access: "{{ env_data_access_role }}"
#     ranger_audit: "{{ env_ranger_audit_role }}"
# - name: Install datalake
#   cloudera.cloud.datalake:
#     name: "{{ cdl_name }}"
#     state: present
#     environment: "{{ env_name }}"
#     instance_profile: "{{ cdl_idbroker_instance_profile }}"
#     storage: "{{ cdl_storage_bucket }}"
#     scale: "{{ cdl_scale }}"
#     tags: "{{ cdl_tags }}"
# - name: Sync idbroker mappings
#   cloudera.cloud.env_user_sync:
#     name: "{{ env_name }}"

# - name: Get environment CRN
#   cloudera.cloud.env_info:
#     name: "{{ env_name }}"
#   register: env_info_out

# - debug:
#     # msg: "{{ env_info_out['environments'][0]['crn'] }}"
#     # msg: "{{ tenant_groups }}"
#     msg: "{{ tenant_groups }}"

# - name: Assign CDP resource roles to ECB CDP tenant groups
#   cloudera.cloud.iam_group:
#     name: "{{ item.0.group_name }}"
#     resource_roles:
#       - {
#           "resource": "{{ env_info_out['environments'][0]['crn'] }}",
#           "role": "{{ tenant_iam_crn }}:resourceRole:{{ item.1 }}",
#         }
#   with_subelements:
#     - "{{ tenant_groups }}"
#     - resource_roles

# - name: Sync environment users
#   cloudera.cloud.env_user_sync:
#     name: "{{ env_name }}"

- name: Retrieve cluster id for CDW cluster
  cloudera.cloud.dw_cluster_info:
    env: "{{ env_name }}"
  register: cdw_cluster_info

# - debug:
#     msg: "{{ cdw_cluster_info }}"
- name: Install CDW virtual warehouse
  cloudera.cloud.dw_virtual_warehouse:
    cluster_id: "{{ cdw_cluster_info['clusters'][0]['id'] }}"
    name: "{{ cdw_vw_impala01['name'] }}"
    type: "{{ cdw_vw_impala01['vw_type'] }}"
    template: "{{ cdw_vw_impala01['template'] }}"
    autoscaling_min_nodes: "{{ cdw_vw_impala01['min_nodes'] }}"
    autoscaling_max_nodes: "{{ cdw_vw_impala01['max_nodes'] }}"
    tags: "{{ cdw_vw_impala01['tags'] }}"
    enable_sso: true
