- name: Enable CDE service
  cloudera.cloud.de:
    name: "{{ item }}"
    env: "{{ env_name }}"
    use_ssd: "{{ cde_clusters[item]['use_ssd'] }}"
    root_volume_size: "{{ cde_clusters[item]['root_vol_size'] }}"
    initial_spot_instances: "{{ cde_clusters[item]['initial_spot_instances'] }}"
    maximum_spot_instances: "{{ cde_clusters[item]['max_spot_instances'] }}"
    minimum_spot_instances: "{{ cde_clusters[item]['min_spot_instances'] }}"
    instance_type: "{{ cde_clusters[item]['instance_type'] }}"
    initial_instances: "{{ cde_clusters[item]['initial_instances'] }}"
    minimum_instances: "{{ cde_clusters[item]['min_instances'] }}"
    maximum_instances: "{{ cde_clusters[item]['max_instances'] }}"
    enable_workload_analytics: false
    enable_public_endpoint: false
    wait: yes
    tags: "{{ cde_clusters[item]['tags'] }}"
  when: action == 'install'

- name: Disable CDE service
  cloudera.cloud.de:
    name: "{{ item }}"
    env: "{{ env_name }}"
    use_ssd: "{{ cde_clusters[item]['use_ssd'] }}"
    root_volume_size: "{{ cde_clusters[item]['root_vol_size'] }}"
    initial_spot_instances: "{{ cde_clusters[item]['initial_spot_instances'] }}"
    maximum_spot_instances: "{{ cde_clusters[item]['max_spot_instances'] }}"
    minimum_spot_instances: "{{ cde_clusters[item]['min_spot_instances'] }}"
    instance_type: "{{ cde_clusters[item]['instance_type'] }}"
    initial_instances: "{{ cde_clusters[item]['initial_instances'] }}"
    minimum_instances: "{{ cde_clusters[item]['min_instances'] }}"
    maximum_instances: "{{ cde_clusters[item]['max_instances'] }}"
    enable_workload_analytics: false
    enable_public_endpoint: false
    wait: yes
    tags: "{{ cde_clusters[item]['tags'] }}"
  with_items: "{{ cde_cluster_names }}"
  when: action == 'delete'
