- name: Install CDP environment
  cloudera.cloud.env:
    name: "{{ env_name }}"
    state: present
    vpc_id: "{{ env_vpc_id }}"
    credential: "{{ env_credential['credential_name'] }}"
    cloud: aws
    region: "{{ env_region }}"
    log_location: "{{ env_log_bucket }}"
    log_identity: "{{ env_log_role_instance_profile }}"
    public_key_text: "{{ env_public_key }}"
    default_sg: "{{ env_sg }}"
    knox_sg: "{{ env_sg }}"
    subnet_ids: "{{ env_subnets }}"
    workload_analytics: "{{ env_workload_analytics }}"
    tags: "{{ env_tags }}"
    tunnel: true
    endpoint_access_scheme: "PRIVATE"
    debug: true

- name: Create data access mappings for ID Broker
  cloudera.cloud.env_idbroker:
    name: "{{ env_name }}"
    data_access: "{{ env_data_access_role }}"
    ranger_audit: "{{ env_ranger_audit_role }}"

- name: Get environment CRN
  cloudera.cloud.env_info:
    name: "{{ env_name }}"
  register: env_info_out

- name: Assign CDP resource roles to ECB CDP tenant groups
  cloudera.cloud.iam_group:
    name: "{{ item.0.group_name }}"
    resource_roles:
      - {
          "resource": "{{ env_info_out['environments'][0]['crn'] }}",
          "role": "{{ tenant_iam_crn }}:resourceRole:{{ item.1 }}",
        }
  with_subelements:
    - "{{ tenant_groups }}"
    - resource_roles

- name: Sync environment users
  cloudera.cloud.env_user_sync:
    name: "{{ env_name }}"
